CREATE ROLE datapusher WITH LOGIN ENCRYPTED PASSWORD 'iTAcdBEcee6GQmJM';
GRANT CREATE, CONNECT, TEMPORARY ON DATABASE datastore TO datapusher;
ALTER USER datapusher WITH SUPERUSER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO datapusher;

CREATE USER datapusher_jobs WITH LOGIN ENCRYPTED PASSWORD 'iTAcdBEcee6GQmJM';
CREATE DATABASE datapusher_jobs OWNER datapusher_jobs ENCODING 'utf-8';
GRANT ALL PRIVILEGES ON DATABASE datapusher_jobs TO datapusher_jobs;